#!/bin/sh

rm -rf  config.log config.status confdefs.h \
       src/*.o src/*.so src/Makevars src/symbols.rds \
       inst/doc/*.blg inst/doc/*.bbl \
       */*~ *~ 
rm -rf autom4te.cache inst/doc/*/auto


